import os
from datetime import date

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from .templates import build_styles


def _sanitize(text: str) -> str:
    """Replace non-Latin-1 characters for ReportLab Helvetica compatibility."""
    if not isinstance(text, str):
        text = str(text)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def build_pdf(papers: list, output_path: str = "outputs/kv_papers_report.pdf") -> str:
    """Generate the 10-page PDF report from a list of Paper dicts."""
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)

    doc = SimpleDocTemplate(
        output_path,
        pagesize=LETTER,
        leftMargin=1 * inch,
        rightMargin=1 * inch,
        topMargin=1 * inch,
        bottomMargin=1 * inch,
    )

    styles = build_styles()
    story = []

    # Cover
    story += _cover_page(styles)
    story.append(PageBreak())

    # Table of Contents
    story += _toc(papers, styles)
    story.append(PageBreak())

    # Executive Summary
    story += _executive_summary(papers, styles)
    story.append(PageBreak())

    # Per-paper sections
    for i, paper in enumerate(papers, 1):
        story += _paper_section(i, paper, styles)
        story.append(PageBreak())

    # Conclusion
    story += _conclusion(papers, styles)

    doc.build(story)
    return output_path


# ── Cover page ───────────────────────────────────────────────────────────────

def _cover_page(styles) -> list:
    elems = []
    elems.append(Spacer(1, 2 * inch))
    elems.append(Paragraph(
        "Position-Independent KV Cache<br/>in Transformer Models",
        styles["CoverTitle"],
    ))
    elems.append(Spacer(1, 0.2 * inch))
    elems.append(Paragraph(
        "A Survey of 5 Papers from Top ML/NLP Venues (2022–2025)",
        styles["SubTitle"],
    ))
    elems.append(Spacer(1, 0.5 * inch))
    elems.append(HRFlowable(width="60%", thickness=1, color=colors.HexColor("#1a1a2e")))
    elems.append(Spacer(1, 0.4 * inch))
    elems.append(Paragraph("Generated by LangGraph ReAct Agent", styles["CoverMeta"]))
    elems.append(Paragraph(
        f"Report Date: {date.today().strftime('%B %d, %Y')}",
        styles["CoverMeta"],
    ))
    elems.append(Paragraph("Model: claude-sonnet-4-6", styles["CoverMeta"]))
    return elems


# ── Table of Contents ─────────────────────────────────────────────────────────

def _toc(papers: list, styles) -> list:
    """Hardcoded TOC based on the fixed 10-page structure."""
    elems = []
    elems.append(Paragraph("Table of Contents", styles["SectionHeader"]))
    elems.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
    elems.append(Spacer(1, 0.1 * inch))

    # Fixed page mapping: cover=1, toc=2, exec_summary=3, papers=4..N, conclusion=N+1
    exec_page = 3
    paper_start = 4
    conclusion_page = paper_start + len(papers)

    entries = [("Executive Summary", exec_page)]
    for i, p in enumerate(papers, 1):
        title = _sanitize(p.get("title", f"Paper {i}"))
        # Truncate long titles
        if len(title) > 70:
            title = title[:67] + "..."
        entries.append((f"Paper {i}: {title}", paper_start + i - 1))
    entries.append(("Conclusion & Comparative Analysis", conclusion_page))

    toc_data = []
    for section_title, page_num in entries:
        toc_data.append([section_title, str(page_num)])

    t = Table(toc_data, colWidths=[5.5 * inch, 0.5 * inch])
    t.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 11),
        ("LEADING", (0, 0), (-1, -1), 18),
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
        ("LINEBELOW", (0, 0), (-1, -2), 0.3, colors.lightgrey),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    elems.append(t)
    return elems


# ── Executive Summary ─────────────────────────────────────────────────────────

def _executive_summary(papers: list, styles) -> list:
    elems = []
    elems.append(Paragraph("Executive Summary", styles["SectionHeader"]))
    elems.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
    elems.append(Spacer(1, 0.1 * inch))

    count = len(papers)
    venues = list({_sanitize(p.get("venue", "")) for p in papers if p.get("venue")})
    venue_str = ", ".join(venues) if venues else "top-tier ML venues"

    intro = (
        f"This report surveys {count} peer-reviewed paper{'s' if count != 1 else ''} "
        f"addressing position-independent or position-agnostic key-value (KV) cache "
        f"mechanisms in transformer-based models, drawn from {venue_str}. "
        f"KV caches are a foundational component of autoregressive transformer inference, "
        f"enabling efficient reuse of previously computed attention keys and values. "
        f"The papers collected here tackle a critical bottleneck: traditional KV caches "
        f"are tightly coupled to absolute positional encodings, making them difficult to "
        f"reuse across different sequence positions, limiting context reuse, and "
        f"increasing memory overhead at scale."
    )
    elems.append(Paragraph(_sanitize(intro), styles["Body"]))
    elems.append(Spacer(1, 0.1 * inch))

    for i, p in enumerate(papers, 1):
        title = _sanitize(p.get("title", f"Paper {i}"))
        venue = _sanitize(p.get("venue", ""))
        year = p.get("year", "")
        problem_snippet = _sanitize(p.get("problem", ""))
        # Take first ~40 words of problem field
        words = problem_snippet.split()[:40]
        snippet = " ".join(words)
        if len(problem_snippet.split()) > 40:
            snippet += "..."
        entry = (
            f"<b>Paper {i}</b> — <i>{title}</i> ({venue} {year}) addresses: {snippet}"
        )
        elems.append(Paragraph(entry, styles["Body"]))
        elems.append(Spacer(1, 0.05 * inch))

    closing = (
        "Together, these works reflect a growing recognition in the research community "
        "that position independence is key to scalable, reusable KV caches. The approaches "
        "span architectural innovations, training-time objectives, and inference-time "
        "compression strategies — collectively advancing the state of the art in "
        "efficient transformer inference."
    )
    elems.append(Spacer(1, 0.1 * inch))
    elems.append(Paragraph(_sanitize(closing), styles["Body"]))
    return elems


# ── Per-paper section ─────────────────────────────────────────────────────────

def _paper_section(index: int, paper: dict, styles) -> list:
    """Render one paper as a structured sub-report (~1 page)."""
    elems = []

    title = _sanitize(paper.get("title", "Untitled"))
    authors = _sanitize(paper.get("authors", "Unknown"))
    venue = _sanitize(paper.get("venue", ""))
    year = paper.get("year", "")
    url = _sanitize(paper.get("url", ""))

    # Section header
    elems.append(Paragraph(
        f"Paper {index} of {5}",
        styles["SectionHeader"],
    ))
    elems.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#16213e")))
    elems.append(Spacer(1, 0.05 * inch))

    # Metadata table
    header_data = [
        ["Title", title],
        ["Authors", authors],
        ["Venue / Year", f"{venue} {year}"],
        ["URL", url],
    ]
    t = Table(header_data, colWidths=[1.2 * inch, 5.3 * inch])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#e8f4f8")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1),
         [colors.HexColor("#f0f8ff"), colors.white]),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    elems.append(t)
    elems.append(Spacer(1, 0.1 * inch))

    # Five structured fields
    fields = [
        ("Problem Description", "problem"),
        ("Motivation", "motivation"),
        ("Issues & Challenges", "issues"),
        ("Proposed Approach", "approach"),
        ("Key Experimental Findings", "key_findings"),
    ]
    for label, key in fields:
        elems.append(Paragraph(label, styles["FieldLabel"]))
        content = _sanitize(paper.get(key, "N/A"))
        elems.append(Paragraph(content, styles["Body"]))
        elems.append(HRFlowable(
            width="100%", thickness=0.3, color=colors.lightgrey, spaceAfter=4,
        ))
    return elems


# ── Conclusion ────────────────────────────────────────────────────────────────

def _conclusion(papers: list, styles) -> list:
    elems = []
    elems.append(Paragraph("Conclusion & Comparative Analysis", styles["SectionHeader"]))
    elems.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
    elems.append(Spacer(1, 0.1 * inch))

    intro = (
        "The five papers surveyed in this report collectively advance the understanding "
        "of position-independent KV cache mechanisms in transformer architectures. "
        "Each work tackles the fundamental challenge of decoupling cached key-value "
        "representations from absolute positional coordinates, enabling more flexible "
        "context reuse, reduced memory footprint, and improved generalization to "
        "out-of-distribution sequence lengths."
    )
    elems.append(Paragraph(_sanitize(intro), styles["Body"]))
    elems.append(Spacer(1, 0.15 * inch))

    # Comparative table
    elems.append(Paragraph("Comparative Overview", styles["FieldLabel"]))
    elems.append(Spacer(1, 0.05 * inch))

    table_data = [["#", "Title (abbreviated)", "Venue", "Year", "Core Technique"]]
    for i, p in enumerate(papers, 1):
        title = _sanitize(p.get("title", ""))
        if len(title) > 40:
            title = title[:37] + "..."
        approach_words = _sanitize(p.get("approach", "")).split()[:8]
        technique = " ".join(approach_words) + ("..." if len(approach_words) >= 8 else "")
        table_data.append([
            str(i),
            title,
            _sanitize(p.get("venue", "")),
            str(p.get("year", "")),
            technique,
        ])

    col_widths = [0.25 * inch, 2.2 * inch, 0.9 * inch, 0.5 * inch, 2.65 * inch]
    t = Table(table_data, colWidths=col_widths)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1),
         [colors.HexColor("#f0f8ff"), colors.white]),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    elems.append(t)
    elems.append(Spacer(1, 0.15 * inch))

    closing = (
        "Taken together, these contributions signal a paradigm shift: future transformer "
        "systems are likely to adopt position-agnostic KV representations as a default, "
        "enabling longer contexts, better cache sharing across requests, and more "
        "memory-efficient inference. Open challenges include maintaining positional "
        "fidelity for tasks that require precise ordering, scaling these techniques to "
        "multi-modal settings, and developing unified benchmarks for position-independent "
        "KV cache evaluation."
    )
    elems.append(Paragraph(_sanitize(closing), styles["Body"]))
    return elems
